version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 3000
  AfterInstall:
    - location: fix_privileges.sh
      timeout: 300
  ApplicationStart:
    - location: server_start.sh
      timeout: 200
  ApplicationStop:
    - location: server_stop.sh
      timeout: 200